/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lee Li
 */
public class MakingPizza extends javax.swing.JFrame {

     double perpizzaforlabour = 0.75;
        double perpizzaforpizzashop = 0.99;
        double perpizzaforingredients = 0.50;
        
        double Subtotal;
        double Grandtotal;
        double Taxes; 
        int centimeter;

    
    public MakingPizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        lblPutridPizza = new javax.swing.JLabel();
        lblDiameterofpizza = new javax.swing.JLabel();
        txtDiameterofpizza = new javax.swing.JTextField();
        lblSubtotal = new javax.swing.JLabel();
        lblTaxes = new javax.swing.JLabel();
        lblGrandtotal = new javax.swing.JLabel();
        lblyouarewelcome = new javax.swing.JLabel();
        btnCaculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPutridPizza.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        lblPutridPizza.setForeground(new java.awt.Color(255, 102, 102));
        lblPutridPizza.setText("Putrid Pizza");
        lblPutridPizza.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblPutridPizza.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);

        lblDiameterofpizza.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblDiameterofpizza.setText("Diameter of pizza");

        txtDiameterofpizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiameterofpizzaActionPerformed(evt);
            }
        });

        lblSubtotal.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblSubtotal.setText("Subtotal ");
        lblSubtotal.setAlignmentY(2.0F);

        lblTaxes.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblTaxes.setText("Taxes");
        lblTaxes.setAlignmentX(2.0F);
        lblTaxes.setAlignmentY(2.0F);

        lblGrandtotal.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblGrandtotal.setText("Grandtotal");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lblGrandtotal, org.jdesktop.beansbinding.ELProperty.create("${background.alpha}"), lblGrandtotal, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        lblyouarewelcome.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        lblyouarewelcome.setText("You are welocme !");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lblyouarewelcome, org.jdesktop.beansbinding.ELProperty.create("${toolTipText}"), lblyouarewelcome, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        btnCaculate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCaculate.setText("Caculate");
        btnCaculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtotal)
                    .addComponent(lblGrandtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTaxes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(563, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPutridPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblyouarewelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lblDiameterofpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDiameterofpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176)
                .addComponent(btnCaculate)
                .addGap(0, 123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblPutridPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiameterofpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCaculate)
                    .addComponent(lblDiameterofpizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTaxes)
                .addGap(31, 31, 31)
                .addComponent(lblGrandtotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(lblyouarewelcome)
                .addGap(84, 84, 84))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiameterofpizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiameterofpizzaActionPerformed
   
       centimeter = Integer.parseInt(txtDiameterofpizza.getText());
       
    }//GEN-LAST:event_txtDiameterofpizzaActionPerformed

    private void btnCaculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaculateActionPerformed
        
        centimeter = Integer.parseInt(txtDiameterofpizza.getText());
       
        Subtotal = perpizzaforlabour + perpizzaforpizzashop + centimeter * 0.50;
        
        lblSubtotal.setText(String.valueOf(Subtotal));
        
        Taxes = (0.75 + 0.99 + centimeter * 0.50) * 0.13;
        
        lblTaxes.setText(String.valueOf(Taxes));
        
        Grandtotal = Taxes + Subtotal;
        
        lblGrandtotal.setText(String.valueOf(Grandtotal));
        
         if (centimeter<=15)
        { 
            System.out.println("We are going to make you a cute pizza ! ");
        }
        else if (centimeter>20)
        {
            System.out.println("This will be delicious.");
        }
        else if (centimeter>40)
        {
            System.out.println("Whoa! Big pizza. You might need a truck for it.");
        }
        
   
    }//GEN-LAST:event_btnCaculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakingPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakingPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakingPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakingPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakingPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaculate;
    private javax.swing.JLabel lblDiameterofpizza;
    private javax.swing.JLabel lblGrandtotal;
    private javax.swing.JLabel lblPutridPizza;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTaxes;
    private javax.swing.JLabel lblyouarewelcome;
    private javax.swing.JTextField txtDiameterofpizza;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
